export const ADD_INGREDIENT= 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT= 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS='SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FIALED'

export const PURCHASE_BURGER_SUCCESS= 'PRHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL= 'PRCHASE_BURGER_FAIL'
export const PURCHASE_BURGER_START= 'PRCHASE_BURGER_START'
export const PURCHASE_INIT= 'PRCHASE_INIT'
